# Generated by Django 3.0.4 on 2020-03-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200313_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='is_following', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
