# Generated by Django 3.0.4 on 2020-03-14 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200314_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
