# Generated by Django 3.0.4 on 2020-03-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_connection_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Greenville', max_length=255),
            preserve_default=False,
        ),
    ]
