# Generated by Django 3.0.4 on 2020-03-09 17:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('BKFST', 'Breakfast'), ('LNCH', 'Lunch'), ('DIN', 'Dinner'), ('DSSRT', 'Dessert')], max_length=10)),
                ('prep_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cook_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cook_temp', models.CharField(choices=[('F', 'Farenheit'), ('C', 'Celsius')], max_length=10)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
