# Generated by Django 3.0.4 on 2020-03-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cook_temp',
            new_name='cook_scale',
        ),
    ]
