# Generated by Django 3.0.4 on 2020-03-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200311_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='personal_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
