# Generated by Django 3.0.4 on 2020-03-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200311_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='created_by',
            new_name='owner',
        ),
    ]
