# Generated by Django 3.0.5 on 2020-04-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_forecast_ingredient_location_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forecast',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
